// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using srvProduct.DB;

#nullable disable

namespace srvProduct.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230908122418_CategoryV3")]
    partial class CategoryV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("srvProduct.DB.tblCategoryDetail", b =>
                {
                    b.Property<Guid>("CategoryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("CategoryDetailId");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblCategoryDetail");
                });

            modelBuilder.Entity("srvProduct.DB.tblCategoryMaster", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("tblCategoryMaster");
                });

            modelBuilder.Entity("srvProduct.DB.tblProperty", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Options")
                        .HasMaxLength(258)
                        .HasColumnType("varchar(258)");

                    b.Property<int>("PropertyDisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Regx")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("SubCategoryDetailId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("SubCategoryDetailId");

                    b.ToTable("tblProperty");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryDetail", b =>
                {
                    b.Property<Guid>("SubCategoryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("SubCategoryDetailId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("tblSubCategoryDetail");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryMaster", b =>
                {
                    b.Property<Guid>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifiedDt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblSubCategoryMaster");
                });

            modelBuilder.Entity("srvProduct.DB.tblCategoryDetail", b =>
                {
                    b.HasOne("srvProduct.DB.tblCategoryMaster", "tblCategoryMaster")
                        .WithMany("CategoryDetail")
                        .HasForeignKey("CategoryId");

                    b.Navigation("tblCategoryMaster");
                });

            modelBuilder.Entity("srvProduct.DB.tblProperty", b =>
                {
                    b.HasOne("srvProduct.DB.tblSubCategoryDetail", "tblSubCategoryDetail")
                        .WithMany("Properties")
                        .HasForeignKey("SubCategoryDetailId");

                    b.Navigation("tblSubCategoryDetail");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryDetail", b =>
                {
                    b.HasOne("srvProduct.DB.tblSubCategoryMaster", "tblSubCategoryMaster")
                        .WithMany("SubCategoryDetail")
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("tblSubCategoryMaster");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryMaster", b =>
                {
                    b.HasOne("srvProduct.DB.tblCategoryMaster", "tblCategoryMaster")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("tblCategoryMaster");
                });

            modelBuilder.Entity("srvProduct.DB.tblCategoryMaster", b =>
                {
                    b.Navigation("CategoryDetail");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryDetail", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("srvProduct.DB.tblSubCategoryMaster", b =>
                {
                    b.Navigation("SubCategoryDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
